//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SubredditComments = newSubredditCommentsTable("public", "subreddit_comments", "")

type subredditCommentsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	Content         postgres.ColumnString
	Image           postgres.ColumnString
	NumberOfVotes   postgres.ColumnInteger
	OwnerHandle     postgres.ColumnString
	ParentCommentID postgres.ColumnString
	PostID          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SubredditCommentsTable struct {
	subredditCommentsTable

	EXCLUDED subredditCommentsTable
}

// AS creates new SubredditCommentsTable with assigned alias
func (a SubredditCommentsTable) AS(alias string) *SubredditCommentsTable {
	return newSubredditCommentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubredditCommentsTable with assigned schema name
func (a SubredditCommentsTable) FromSchema(schemaName string) *SubredditCommentsTable {
	return newSubredditCommentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubredditCommentsTable with assigned table prefix
func (a SubredditCommentsTable) WithPrefix(prefix string) *SubredditCommentsTable {
	return newSubredditCommentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubredditCommentsTable with assigned table suffix
func (a SubredditCommentsTable) WithSuffix(suffix string) *SubredditCommentsTable {
	return newSubredditCommentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubredditCommentsTable(schemaName, tableName, alias string) *SubredditCommentsTable {
	return &SubredditCommentsTable{
		subredditCommentsTable: newSubredditCommentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newSubredditCommentsTableImpl("", "excluded", ""),
	}
}

func newSubredditCommentsTableImpl(schemaName, tableName, alias string) subredditCommentsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		ContentColumn         = postgres.StringColumn("content")
		ImageColumn           = postgres.StringColumn("image")
		NumberOfVotesColumn   = postgres.IntegerColumn("number_of_votes")
		OwnerHandleColumn     = postgres.StringColumn("owner_handle")
		ParentCommentIDColumn = postgres.StringColumn("parent_comment_id")
		PostIDColumn          = postgres.StringColumn("post_id")
		allColumns            = postgres.ColumnList{IDColumn, ContentColumn, ImageColumn, NumberOfVotesColumn, OwnerHandleColumn, ParentCommentIDColumn, PostIDColumn}
		mutableColumns        = postgres.ColumnList{ContentColumn, ImageColumn, NumberOfVotesColumn, OwnerHandleColumn, ParentCommentIDColumn, PostIDColumn}
	)

	return subredditCommentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Content:         ContentColumn,
		Image:           ImageColumn,
		NumberOfVotes:   NumberOfVotesColumn,
		OwnerHandle:     OwnerHandleColumn,
		ParentCommentID: ParentCommentIDColumn,
		PostID:          PostIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
