//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Followage = Followage.FromSchema(schema)
	PostTags = PostTags.FromSchema(schema)
	SubredditComments = SubredditComments.FromSchema(schema)
	SubredditPosts = SubredditPosts.FromSchema(schema)
	Subreddits = Subreddits.FromSchema(schema)
	UserAdminedSubreddits = UserAdminedSubreddits.FromSchema(schema)
	UserComments = UserComments.FromSchema(schema)
	UserJoinedSubreddits = UserJoinedSubreddits.FromSchema(schema)
	UserPosts = UserPosts.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
