//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserJoinedSubreddits = newUserJoinedSubredditsTable("public", "user_joined_subreddits", "")

type userJoinedSubredditsTable struct {
	postgres.Table

	// Columns
	UserHandle      postgres.ColumnString
	SubredditHandle postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserJoinedSubredditsTable struct {
	userJoinedSubredditsTable

	EXCLUDED userJoinedSubredditsTable
}

// AS creates new UserJoinedSubredditsTable with assigned alias
func (a UserJoinedSubredditsTable) AS(alias string) *UserJoinedSubredditsTable {
	return newUserJoinedSubredditsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserJoinedSubredditsTable with assigned schema name
func (a UserJoinedSubredditsTable) FromSchema(schemaName string) *UserJoinedSubredditsTable {
	return newUserJoinedSubredditsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserJoinedSubredditsTable with assigned table prefix
func (a UserJoinedSubredditsTable) WithPrefix(prefix string) *UserJoinedSubredditsTable {
	return newUserJoinedSubredditsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserJoinedSubredditsTable with assigned table suffix
func (a UserJoinedSubredditsTable) WithSuffix(suffix string) *UserJoinedSubredditsTable {
	return newUserJoinedSubredditsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserJoinedSubredditsTable(schemaName, tableName, alias string) *UserJoinedSubredditsTable {
	return &UserJoinedSubredditsTable{
		userJoinedSubredditsTable: newUserJoinedSubredditsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newUserJoinedSubredditsTableImpl("", "excluded", ""),
	}
}

func newUserJoinedSubredditsTableImpl(schemaName, tableName, alias string) userJoinedSubredditsTable {
	var (
		UserHandleColumn      = postgres.StringColumn("user_handle")
		SubredditHandleColumn = postgres.StringColumn("subreddit_handle")
		allColumns            = postgres.ColumnList{UserHandleColumn, SubredditHandleColumn}
		mutableColumns        = postgres.ColumnList{}
	)

	return userJoinedSubredditsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserHandle:      UserHandleColumn,
		SubredditHandle: SubredditHandleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
