//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPosts = newUserPostsTable("public", "user_posts", "")

type userPostsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	Title           postgres.ColumnString
	Content         postgres.ColumnString
	Image           postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	NumberOfVotes   postgres.ColumnInteger
	IsPinned        postgres.ColumnBool
	OwnerHandle     postgres.ColumnString
	SubredditHandle postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserPostsTable struct {
	userPostsTable

	EXCLUDED userPostsTable
}

// AS creates new UserPostsTable with assigned alias
func (a UserPostsTable) AS(alias string) *UserPostsTable {
	return newUserPostsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPostsTable with assigned schema name
func (a UserPostsTable) FromSchema(schemaName string) *UserPostsTable {
	return newUserPostsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPostsTable with assigned table prefix
func (a UserPostsTable) WithPrefix(prefix string) *UserPostsTable {
	return newUserPostsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPostsTable with assigned table suffix
func (a UserPostsTable) WithSuffix(suffix string) *UserPostsTable {
	return newUserPostsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPostsTable(schemaName, tableName, alias string) *UserPostsTable {
	return &UserPostsTable{
		userPostsTable: newUserPostsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newUserPostsTableImpl("", "excluded", ""),
	}
}

func newUserPostsTableImpl(schemaName, tableName, alias string) userPostsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		TitleColumn           = postgres.StringColumn("title")
		ContentColumn         = postgres.StringColumn("content")
		ImageColumn           = postgres.StringColumn("image")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		NumberOfVotesColumn   = postgres.IntegerColumn("number_of_votes")
		IsPinnedColumn        = postgres.BoolColumn("is_pinned")
		OwnerHandleColumn     = postgres.StringColumn("owner_handle")
		SubredditHandleColumn = postgres.StringColumn("subreddit_handle")
		allColumns            = postgres.ColumnList{IDColumn, TitleColumn, ContentColumn, ImageColumn, CreatedAtColumn, NumberOfVotesColumn, IsPinnedColumn, OwnerHandleColumn, SubredditHandleColumn}
		mutableColumns        = postgres.ColumnList{TitleColumn, ContentColumn, ImageColumn, CreatedAtColumn, NumberOfVotesColumn, IsPinnedColumn, OwnerHandleColumn, SubredditHandleColumn}
	)

	return userPostsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Title:           TitleColumn,
		Content:         ContentColumn,
		Image:           ImageColumn,
		CreatedAt:       CreatedAtColumn,
		NumberOfVotes:   NumberOfVotesColumn,
		IsPinned:        IsPinnedColumn,
		OwnerHandle:     OwnerHandleColumn,
		SubredditHandle: SubredditHandleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
