//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Subreddits struct {
	Handle    string `sql:"primary_key"`
	Title     string
	About     *string
	Avatar    []byte
	Rules     *string
	CreatedAt time.Time
}
